/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 *  @authors Group C 
 */
public class PlugInView extends javax.swing.JFrame {

    
        private MinionsController mainCtrl;
        private String playersName;
        public String PLACE_HOLDER = "Nick Name";
    
    
       /**
     * Creates new form PlugIn
     */
    public PlugInView( MinionsController mainCtrl) throws RemoteException {
        initComponents();
        this.mainCtrl = mainCtrl;
        
    }
    
    /**
     * Creates new form PlugIn
     */
    public PlugInView()  throws RemoteException{
        initComponents();
    }

    public String getPlayersName() {
        return playersName;
    }

    public void setPlayersName(String playersName) {
        this.playersName = playersName;
    }

    public JTextField getNickNameTxt() {
        return nickNameTxt;
    }

       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nickNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pluginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::FEED THE MINION GAME::");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1020, 601));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        nickNameTxt.setBackground(new java.awt.Color(102, 102, 102));
        nickNameTxt.setFont(new java.awt.Font("FreeSerif", 0, 18)); // NOI18N
        nickNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nickNameTxt.setText(" ");
        nickNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nickNameTxtMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nickNameTxtMouseClicked(evt);
            }
        });
        nickNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickNameTxtActionPerformed(evt);
            }
        });
        nickNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nickNameTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nickNameTxtKeyReleased(evt);
            }
        });
        jPanel1.add(nickNameTxt);
        nickNameTxt.setBounds(10, 58, 240, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nick-Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 240, 30);

        jLabel2.setFont(new java.awt.Font("Ubuntu Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FEED THE MINION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 190, 300, 70);

        pluginButton.setBackground(java.awt.Color.darkGray);
        pluginButton.setForeground(new java.awt.Color(255, 255, 255));
        pluginButton.setText("PLAY");
        pluginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pluginButton);
        pluginButton.setBounds(260, 58, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minionIcon.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 610);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(950, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pluginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluginButtonActionPerformed
       mainCtrl.pluginPlayer();
    }//GEN-LAST:event_pluginButtonActionPerformed

    private void nickNameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nickNameTxtMouseClicked
     }//GEN-LAST:event_nickNameTxtMouseClicked

    private void nickNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickNameTxtActionPerformed
     }//GEN-LAST:event_nickNameTxtActionPerformed

    private void nickNameTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nickNameTxtMouseReleased
     }//GEN-LAST:event_nickNameTxtMouseReleased

    private void nickNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nickNameTxtKeyPressed
     }//GEN-LAST:event_nickNameTxtKeyPressed

    private void nickNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nickNameTxtKeyReleased
     }//GEN-LAST:event_nickNameTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlugInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlugInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlugInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlugInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PlugInView().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(PlugInView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nickNameTxt;
    private javax.swing.JButton pluginButton;
    // End of variables declaration//GEN-END:variables
}
